const getExercises = () => {
  // remplacer id par title ?
  const pathToImages = "../assets/images/";

  return [
    {
      id: 1,
      // image: "../assets/images/restau.png",
      image: `${pathToImages}restau.png`,
      mobileImage: null,
      tags: ["html", "css", "js"],
      link: null,
      class: "restau",
      animation: "restauAnimation",
      text: null,
    },
    {
      id: 2,
      // image: "../assets/images/hello.png",
      image: `${pathToImages}hello.png`,
      mobileImage: null,
      tags: ["html", "css"],
      link: null,
      class: "hello",
      animation: "helloAnimation",
      text: null,
    },
    {
      id: 3,
      // image: "../assets/images/archi.png",
      image: `${pathToImages}archi.png`,
      mobileImage: null,
      tags: ["html", "css"],
      link: null,
      class: "archi",
      animation: "archiAnimation",
      text: null,
    },
    {
      id: 4,
      // image: "../assets/images/fake.png",
      image: `${pathToImages}fake.png`,
      // mobileImage: "../assets/images/fake-mobile.png",
      mobileImage: `${pathToImages}fake-mobile.png`,
      tags: ["html", "scss", "js", "php", "sql"],
      link: null,
      class: "fake",
      animation: "fakeAnimation",
      text: null,
    },
    {
      id: 5,
      // image: "../assets/images/blog.png",
      image: `${pathToImages}blog.png`,
      mobileImage: null,
      tags: ["twig", "bootstrap", "symfony"],
      link: null,
      class: "blog",
      animation: "blogAnimation",
      text: null,
    },
    {
      id: 6,
      // image: "../assets/images/shop.png",
      image: `${pathToImages}shop.png`,
      mobileImage: null,
      tags: ["twig", "bootstrap", "symfony"],
      link: null,
      class: "shop",
      animation: "shopAnimation",
      text: null,
    },
    {
      id: 7,
      // image: "../assets/images/aw.png",
      image: `${pathToImages}aw.png`,
      mobileImage: null,
      tags: ["python"],
      link: null,
      class: "aw",
      animation: "awAnimation",
      text: null,
    },
    {
      id: 8,
      image: null,
      mobileImage: null,
      tags: ["python"],
      link: "https://github.com/requenaGuillaume93400/pdf-merger",
      class: "gitLinks",
      text: "Pdf merger/splitter",
    },
    {
      id: 9,
      image: null,
      mobileImage: null,
      tags: ["python"],
      link: "https://github.com/requenaGuillaume93400/ytb",
      class: "gitLinks",
      text: "YouTube video/audio (single and playlist) downloader",
    },
    {
      id: 10,
      image: "../assets/images/artwork.png",
      mobileImage: null,
      tags: ["react", "scss"],
      link: null,
      class: "artwork",
      animation: "artworkAnimation",
      text: null,
    },
    {
      // TODO test
      id: 11,
      //  Ajouter image ?
      image: null,
      mobileImage: null,
      tags: ["html", "php", "bootstrap"],
      link: "https://github.com/requenaGuillaume93400/blogOC",
      class: "gitLinks",
      text: "Blog php natif (Github)",
    },
    {
      id: 12,
      // Ajouter image ?
      image: null,
      mobileImage: null,
      tags: ["wordpress"],
      link: "https://guillaumereq.sites.3wa.io/cv/chalets-et-caviar-immobilier/",
      class: "gitLinks",
      text: "Wordpress - Chalets & Caviar (Site)",
    },
    {
      id: 13,
      // Ajouter image ?
      image: null,
      mobileImage: null,
      tags: ["symfony", "twig", "bootstrap"],
      link: "https://github.com/requenaGuillaume93400/snowtricks",
      class: "gitLinks",
      text: "Blog symfony - Snowtricks (Github)",
    },
    {
      id: 14,
      // Ajouter image ?
      image: null,
      mobileImage: null,
      tags: ["symfony", "twig", "bootstrap"],
      link: "https://github.com/requenaGuillaume93400/BileMo",
      class: "gitLinks",
      text: "Api Restfull - BileMo (Github)",
    },
    {
      id: 15,
      // Ajouter image ?
      image: null,
      mobileImage: null,
      tags: ["symfony", "twig", "bootstrap"],
      link: "https://github.com/requenaGuillaume93400/todolist",
      class: "gitLinks",
      text: "Upgrade php/symfony versions and add tests - Todolist (Github)",
    },
  ];
};

export default getExercises;
